import Pagination from '@/Components/Pagination';
import AdminLayout from '@/Layouts/AdminLayout';
import { Link, usePage, router } from '@inertiajs/react';

export default function Index({ categories }) {
    const { flash = {} } = usePage().props;
    const destroy = (category) => { if (window.confirm(`Hapus kategori ${category.name}?`)) router.delete(route('admin.categories.destroy', category.id)); };

    return <AdminLayout title="Kategori"><div className="border-b border-slate-200 bg-white px-6 py-6 lg:px-10"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-amber-600">Catalog structure</p><h1 className="mt-2 text-2xl font-semibold text-slate-950">Kategori</h1></div><Link href={route('admin.categories.create')} className="rounded-lg bg-slate-900 px-4 py-2.5 text-center text-sm font-semibold text-white hover:bg-slate-700">Tambah Kategori</Link></div></div><div className="mx-auto max-w-5xl px-6 py-8 lg:px-10">{flash.success && <div className="mb-5 rounded-lg bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-800">{flash.success}</div>}{flash.error && <div className="mb-5 rounded-lg bg-red-50 px-4 py-3 text-sm font-medium text-red-800">{flash.error}</div>}<div className="overflow-x-auto rounded-xl bg-white shadow-sm ring-1 ring-slate-200"><table className="min-w-full divide-y divide-slate-100 text-sm"><thead className="bg-slate-50"><tr>{['Nama', 'Slug', 'Parent', 'Produk', 'Aksi'].map((heading) => <th key={heading} className="px-5 py-3 text-left font-semibold text-slate-600">{heading}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{categories.data.map((category) => <tr key={category.id}><td className="px-5 py-4 font-semibold text-slate-900">{category.name}</td><td className="px-5 py-4 text-slate-500">{category.slug}</td><td className="px-5 py-4 text-slate-600">{category.parent?.name ?? '-'}</td><td className="px-5 py-4 text-slate-600">{category.products_count}</td><td className="px-5 py-4"><div className="flex gap-3"><Link href={route('admin.categories.edit', category.id)} className="font-semibold text-amber-700 hover:text-amber-900">Edit</Link><button type="button" onClick={() => destroy(category)} className="font-semibold text-red-600 hover:text-red-800">Hapus</button></div></td></tr>)}</tbody></table></div><div className="mt-6"><Pagination links={categories.links} /></div></div></AdminLayout>;
}